"use strict";

const regexIsAbsolute = /^[a-zA-Z][a-zA-Z\d+\-.]*:/;

/**
 * Dynamically selects fetch from the environment (browser / node)
 * to avoid crashes if a polyfill is loaded later.
 */
const getFetch = () => {
  if (typeof window !== "undefined" && typeof window.fetch === "function") {
    return window.fetch.bind(window);
  }
  if (typeof globalThis !== "undefined" && typeof globalThis.fetch === "function") {
    return globalThis.fetch.bind(globalThis);
  }
  throw new Error("fetch is not defined. Please verify your environment or add a polyfill.");
};

const validMethods = new Set([
  "GET",
  "POST",
  "PUT",
  "PATCH",
  "DELETE",
  "HEAD",
  "OPTIONS",
  "CONNECT",
  "TRACE",
]);

const defaultResponseParser = async (response) => {
  if (response.status === 204) {
    return null;
  }
  const contentType = response.headers.get("content-type");
  if (contentType && contentType.includes("application/json")) {
    return await response.json();
  }
  const text = await response.text();
  try {
    return JSON.parse(text);
  } catch (err) {
    return text;
  }
};

/**
 * uFetch class: Universal and AI-friendly wrapper for HTTP requests (based on 'fetch').
 * Provides tools to automatically handle relative/absolute URLs, JSON bodies,
 * Authorization headers, Query parameters and abstracts the environment context (Browser vs NodeJS).
 */
class uFetch {
  /**
   * Initializes the HTTP client instance.
   * @param {string} [url=undefined] - (Optional) Default base URL to use in requests.
   * @param {string} [redirect_in_unauthorized=undefined] - (Optional) Route or URL to automatically redirect the client in case of 401 error (Only in Browser environment with window).
   */
  constructor(url = undefined, redirect_in_unauthorized = undefined) {
    this._redirect_in_unauthorized_internal = redirect_in_unauthorized;
    this._basic_authentication = undefined;
    this._bearer_authentication = undefined;
    this._url = url;
    this._defaultHeaders = new Map();

    if (typeof AbortController !== "undefined") {
      this._abortController = new AbortController();
    }
  }

  /**
   * Immediately cancels all in-progress requests generated by this instance
   * that do not have an explicitly overridden AbortSignal. 
   * Internally resets to a new controller to support immediate subsequent requests.
   * @param {any} [reason] - Reason, message, or exception returned in the promise rejection catch (e.g., AbortError).
   */
  abort(reason) {
    if (this._abortController) {
      this._abortController.abort(reason);
      this._abortController = new AbortController();
    }
  }

  /**
   * Configures Basic Auth credentials at the client instance level, injecting them into 'Authorization'.
   * @param {string} username - Plain text username.
   * @param {string} password - Plain text password.
   * @returns {uFetch} Returns the current instance enabling context chaining.
   */
  setBasicAuthorization(username, password) {
    if (
      !username ||
      !password ||
      typeof username !== "string" ||
      typeof password !== "string"
    ) {
      this._basic_authentication = undefined;
      return this;
    }

    const credentials = `${username}:${password}`;
    const base64 =
      typeof Buffer !== "undefined"
        ? Buffer.from(credentials).toString("base64")
        : btoa(credentials);

    this._basic_authentication = `Basic ${base64}`;
    this._bearer_authentication = undefined;
    return this;
  }

  /**
   * @deprecated Use setBasicAuthorization() instead.
   */
  SetBasicAuthorization(username, password) {
    console.warn("DeprecationWarning: uFetch.SetBasicAuthorization() is deprecated. Use uFetch.setBasicAuthorization() instead.");
    return this.setBasicAuthorization(username, password);
  }

  /**
   * @deprecated Use clearAuthorizationHeader() instead.
   */
  ClearAuthorizationHeader() {
    console.warn("DeprecationWarning: uFetch.ClearAuthorizationHeader() is deprecated. Use uFetch.clearAuthorizationHeader() instead.");
    this.clearAuthorizationHeader();
  }

  /**
   * Explicitly completely clears and revokes all authorization headers 
   * stored in memory for this instance (both Basic and Bearer auth).
   */
  clearAuthorizationHeader() {
    this._basic_authentication = undefined;
    this._bearer_authentication = undefined;
  }

  /**
   * Alias for setBasicAuthorization for convenience.
   * @param {string} user 
   * @param {string} password 
   * @returns {uFetch}
   */
  setBasicAuthentication(user, password) {
    return this.setBasicAuthorization(user, password);
  }

  /**
   * @deprecated Use setBasicAuthentication() instead.
   */
  SetBasicAuthentication(user, password) {
    console.warn("DeprecationWarning: uFetch.SetBasicAuthentication() is deprecated. Use uFetch.setBasicAuthentication() instead.");
    return this.setBasicAuthentication(user, password);
  }

  /**
   * Configures a Bearer token for the 'Authorization' header at the instance level.
   * Its activation will explicitly deactivate/overwrite any previously persisted Basic credential.
   * @param {string} key - Token key (e.g., a pure JWT or Access Hash).
   * @returns {uFetch} Returns the class for context chaining.
   */
  setBearerAuthorization(key) {
    this._bearer_authentication = key ? `Bearer ${key}` : undefined;
    if (key) this._basic_authentication = undefined;
    return this;
  }

  /**
   * Adds a global, permanent, and persistent header that will be attached to all future
   * peticiones invocadas por este objeto `uFetch`.
   * @param {string} key - Name of the HTTP header block (e.g. 'Application-Context').
   * @param {string} value - String value of the header.
   */
  addHeader(key, value) {
    this._defaultHeaders.set(key, value);
  }

  _addAuthorizationHeader(headers) {
    if (this._basic_authentication) {
      headers.set("Authorization", this._basic_authentication);
    } else if (this._bearer_authentication) {
      headers.set("Authorization", this._bearer_authentication);
    } else if (headers.get('Authorization')) {
      headers.set("Authorization", headers.get('Authorization'));
    } else {
      headers.delete("Authorization");
    }
  }

  _normalizeHeaders(headers = {}, data = undefined) {
    const h = new Headers();

    // Helper to add headers from various sources
    const addFn = (v, k) => h.append(k, v);

    if (headers instanceof Headers || headers instanceof Map) {
      headers.forEach(addFn);
    } else {
      // iterate over object
      for (const [k, v] of Object.entries(headers)) {
        h.append(k, v);
      }
    }

    // agregar headers por defecto
    for (const [k, v] of this._defaultHeaders.entries()) {
      h.set(k, v);
    }

    // auth
    this._addAuthorizationHeader(h);

    if (!h.has("Content-Type")) {
      const isSpecialBody =
        (typeof FormData !== "undefined" && data instanceof FormData) ||
        (typeof Blob !== "undefined" && data instanceof Blob) ||
        (typeof URLSearchParams !== "undefined" && data instanceof URLSearchParams) ||
        (typeof ReadableStream !== "undefined" && data instanceof ReadableStream) ||
        (typeof ArrayBuffer !== "undefined" && data instanceof ArrayBuffer);

      // Only add application/json if data is not special AND not a string
      // strings are strictly treated as raw bodies unless header says otherwise
      if (!isSpecialBody && data != null && typeof data !== "string") {
        h.append("Content-Type", "application/json");
      }
    }

    // Eliminar Content-Length
    h.delete("Content-Length");

    return h;
  }

  _createBody(data) {
    if (data == null) return undefined;

    // casos especiales
    if (
      (typeof FormData !== "undefined" && data instanceof FormData) ||
      (typeof Blob !== "undefined" && data instanceof Blob) ||
      (typeof URLSearchParams !== "undefined" && data instanceof URLSearchParams) ||
      (typeof ReadableStream !== "undefined" && data instanceof ReadableStream) ||
      (typeof ArrayBuffer !== "undefined" && data instanceof ArrayBuffer) ||
      typeof data === "string"
    ) {
      return data;
    }

    // fallback → JSON
    return JSON.stringify(data);
  }

  /**
   * Low-level core engine to execute an asynchronous network request using the Fetch API.
   * Automatically injects Authorization headers and handles smart serialization.
   * 
   * @param {string} url - Final absolute URL, or internal relative path.
   * @param {string} [method="GET"] - HTTP verb in uppercase (GET, POST, PUT, DELETE, PATCH, etc).
   * @param {any} [data=undefined] - The body payload. For GET/HEAD it's sent as a querystring, for other verbs it is automatically converted to a JSON body unless it's a native Stream/Blob/FormData.
   * @param {Object} [headers={}] - Additional dictionary of ephemeral headers living only for this specific transaction.
   * @param {RequestInit} [options={}] - Base object for strict overriding of primitive Fetch options (Credentials, Caching, Mode, custom Signal, etc).
   * @returns {Promise<Response>} Promise resolving to the Fetch Response object.
   * @throws Exception when asynchronous URL validation fails locally or fetch explicitly fails.
   */
  async request(
    url,
    method = "GET",
    data = undefined,
    headers = {},
    options = {},
  ) {
    method = method.toUpperCase();

    if (!validMethods.has(method)) {
      throw new Error("Invalid method");
    }

    let finalURL = url || this._url;

    if (url && this._url && !regexIsAbsolute.test(url)) {
      try {
        finalURL = new URL(url, this._url).toString();
      } catch (e) {
        // Fallback to original validation if URL resolution fails
      }
    }

    // URL Validation using try-catch for better compatibility
    const baseURL =
      typeof window !== "undefined" ? window.location.href : "http://localhost";
    try {
      new URL(finalURL, baseURL);
    } catch (e) {
      console.error("Is required a valid URL", finalURL);
      throw new Error("Is required a valid URL " + finalURL);
    }

    const h = this._normalizeHeaders(headers, data);

    // GET / HEAD → data como querystring
    if (["GET", "HEAD"].includes(method) && data && typeof data === "object") {
      const sp = new URLSearchParams(data);
      const queryString = sp.toString();
      if (queryString) {
        const hashIndex = finalURL.indexOf("#");
        let hash = "";
        let urlWithoutHash = finalURL;

        if (hashIndex !== -1) {
          hash = finalURL.substring(hashIndex);
          urlWithoutHash = finalURL.substring(0, hashIndex);
        }

        const separator = urlWithoutHash.includes("?") ? "&" : "?";
        finalURL = urlWithoutHash + separator + queryString + hash;
      }
    }

    const body = !["GET", "HEAD"].includes(method)
      ? this._createBody(data)
      : undefined;

    const opts = {
      method,
      headers: h,
      body,
      ...(this._abortController ? { signal: this._abortController.signal } : {}),
      ...options,
    };

    let response;
    try {
      const fetchImpl = getFetch();
      response = await fetchImpl(finalURL, opts);

      if (
        typeof window !== "undefined" &&
        this._redirect_in_unauthorized_internal &&
        response.status === 401
      ) {
        window.location.href = this._redirect_in_unauthorized_internal;
      }

      return response;
    } catch (err) {
      console.error(err);
      throw err;
    }
  }

  // Simplified Methods

  /**
   * Triggers a read query ("GET" verb). Automatically and transparently serializes `opts.data` using search query strings (e.g., url?foo=bar).
   * @param {{url?: string, data?: any, headers?: Object, options?: RequestInit}} opts - Configuration wrapper object (URL, simulated body Data, local headers and init options).
   * @returns {Promise<Response>} Original HTTP Promise from the `fetch` API.
   */
  get(opts = {}) {
    return this.request(opts.url, "GET", opts.data, opts.headers, opts.options);
  }

  /** @deprecated Use get() instead. */
  GET(opts = {}) {
    console.warn("DeprecationWarning: uFetch.GET() is deprecated. Use uFetch.get() instead.");
    return this.get(opts);
  }

  /**
   * Triggers a mutation/insertion via an endpoint consuming a "POST" verb.
   * By default, stringifies the `data` to JSON without encoding, overriding the 'application/json' flag if it is plain.
   * @param {{url?: string, data?: any, headers?: Object, options?: RequestInit}} opts
   * @returns {Promise<Response>}
   */
  post(opts = {}) {
    return this.request(
      opts.url,
      "POST",
      opts.data,
      opts.headers,
      opts.options,
    );
  }

  /** @deprecated Use post() instead. */
  POST(opts = {}) {
    console.warn("DeprecationWarning: uFetch.POST() is deprecated. Use uFetch.post() instead.");
    return this.post(opts);
  }

  /**
   * Replaces existing information by injecting the complete data payload to the router using the "PUT" verb.
   * @param {{url?: string, data?: any, headers?: Object, options?: RequestInit}} opts
   * @returns {Promise<Response>}
   */
  put(opts = {}) {
    return this.request(opts.url, "PUT", opts.data, opts.headers, opts.options);
  }

  /** @deprecated Use put() instead. */
  PUT(opts = {}) {
    console.warn("DeprecationWarning: uFetch.PUT() is deprecated. Use uFetch.put() instead.");
    return this.put(opts);
  }

  /**
   * Controlled backend partial mutation dictated by the "PATCH" verb, modifying fragments.
   * @param {{url?: string, data?: any, headers?: Object, options?: RequestInit}} opts
   * @returns {Promise<Response>}
   */
  patch(opts = {}) {
    return this.request(
      opts.url,
      "PATCH",
      opts.data,
      opts.headers,
      opts.options,
    );
  }

  /** @deprecated Use patch() instead. */
  PATCH(opts = {}) {
    console.warn("DeprecationWarning: uFetch.PATCH() is deprecated. Use uFetch.patch() instead.");
    return this.patch(opts);
  }

  /**
   * Orders to clear / destroy a resource tuple pointed at by `url` by sending a "DELETE" verb.
   * @param {{url?: string, data?: any, headers?: Object, options?: RequestInit}} opts
   * @returns {Promise<Response>}
   */
  delete(opts = {}) {
    return this.request(
      opts.url,
      "DELETE",
      opts.data,
      opts.headers,
      opts.options,
    );
  }

  /** @deprecated Use delete() instead. */
  DELETE(opts = {}) {
    console.warn("DeprecationWarning: uFetch.DELETE() is deprecated. Use uFetch.delete() instead.");
    return this.delete(opts);
  }

  /**
   * Processes an array of items in parallel batches with a configured concurrency limit (Pool).
   * Highly optimized for AI Agents and bulk data processing.
   * 
   * NOTE: The signature batch(url, method, items, headers, options, config) with positional arguments
   * is deprecated and will now throw an exception. Use the single configuration object instead.
   * If you explicitly need to use positional parameters, use the batch_old() method.
   * 
   * NOTE ON URL PARAMETER:
   * The `url` field in the batch input parameters is optional. It should only be used if the URL was not passed to the class constructor, or if you explicitly want to override/change the URL defined in the class constructor.
   * 
   * SPECIFICATIONS FOR THE 'items' PROPERTY (CRITICAL FOR AI AGENTS):
   * The 'items' parameter must be an Array. Each element in the array is processed as a separate request and can be:
   * 1. A RAW PAYLOAD: A primitive value or a plain object without special keys (e.g. `{ edad: 12 }` or `"some-id"`).
   *    - It is automatically treated as the request `data` (sent as the request body or query string according to the HTTP method).
   * 2. An OVERRIDE-CONFIG OBJECT: An object containing any of these special keys: `{ url, method, data, headers, options }`.
   *    - It merges with and overrides the base configuration parameters for that specific item's request (e.g. changing the endpoint or the method for a single item).
   *    - When using this form, the actual payload to be sent must be placed inside the `data` key (e.g. `{ data: { edad: 12 }, url: "/special-endpoint", method: "POST" }`).
   *    - If you pass an object with other keys (like `{ name: "Edwin", url: "/users" }`) and it doesn't have a `data` key, the entire object is treated as the payload (`data`) but the `url` (and other special keys) are extracted as overrides.
   * 
   * @param {Object} opts - Configuration options for the batch request.
   * @param {string} [opts.url] - (Optional) Base URL for requests (fallback). Should only be used when no URL was passed in the constructor, or if you explicitly want to change the URL defined in the constructor.
   * @param {string} [opts.method="GET"] - Base HTTP verb (fallback).
   * @param {Array<any>} opts.items - Collection to process. Supports raw data or override-config objects.
   * @param {Object} [opts.headers={}] - Base headers to merge.
   * @param {Object} [opts.options={}] - Base Fetch options (RequestInit).
   * @param {Object} [opts.config={}] - Batch settings.
   * @param {number} [opts.config.concurrency=5] - Parallel worker limit.
   * @param {Function} [opts.config.onProgress] - Callback invoked after each request resolution: (info) => void.
   * @param {Function} [opts.config.responseParser] - (Optional) Custom extractor function for the response payload: async (response) => data.
   * @param {boolean} [opts.config.includeResponse=false] - (Optional) If true, includes the raw Fetch 'response' object in the result descriptor.
   * @returns {Promise<Array<{isError: boolean, httpCode: number|null, data?: any, response?: Response, error?: any}>>} Array of result descriptors (ordered).
   */
  async batch(opts = {}) {
    if (arguments.length > 1) {
      throw new Error(
        "uFetch.batch() now only accepts a single configuration object parameter. " +
        "If you need to use the deprecated positional arguments signature, please use uFetch.batch_old() instead."
      );
    }

    if (typeof opts !== "object" || opts === null || Array.isArray(opts)) {
      throw new Error(
        "uFetch.batch() expects a single configuration object containing options (e.g., { url, method, items, headers, options, config }). " +
        "To use the deprecated positional arguments signature, please use uFetch.batch_old() instead."
      );
    }

    if (!opts.hasOwnProperty("items")) {
      throw new Error("uFetch.batch() requires the 'items' parameter inside the configuration object.");
    }

    const {
      url,
      method: reqMethod = "GET",
      items: reqItems = [],
      headers: reqHeaders = {},
      options: reqOptions = {},
      config: reqConfig = {},
    } = opts;

    const {
      concurrency = 5,
      onProgress,
      responseParser,
      includeResponse = false,
    } = reqConfig;

    if (!Array.isArray(reqItems)) {
      throw new Error("batch() expects an array of items");
    }

    const total = reqItems.length;
    const results = new Array(total);
    let currentIndex = 0;
    let completed = 0;

    const worker = async () => {
      while (currentIndex < total) {
        const index = currentIndex++;
        const item = reqItems[index];
        let resultPayload;
        let response = null;

        try {
          let reqUrl = url;
          let reqMethodVal = reqMethod;
          let reqData = item;
          let reqHeadersVal = reqHeaders;
          let reqOptionsVal = reqOptions;

          // Smart detection: if item is an object that looks like a request config, use it to override base params
          if (
            typeof item === "object" &&
            item !== null &&
            (item.url || item.method || item.hasOwnProperty("data") || item.headers || item.options)
          ) {
            reqUrl = item.url || url;
            reqMethodVal = item.method || reqMethod;
            reqData = item.hasOwnProperty("data") ? item.data : item;
            reqHeadersVal = item.headers ? { ...reqHeaders, ...item.headers } : reqHeaders;
            reqOptionsVal = item.options ? { ...reqOptions, ...item.options } : reqOptions;
          }

          response = await this.request(
            reqUrl,
            reqMethodVal,
            reqData,
            reqHeadersVal,
            reqOptionsVal
          );

          const parser = responseParser || defaultResponseParser;
          const parsedData = await parser(response);

          resultPayload = {
            isError: false,
            httpCode: response.status,
            data: parsedData,
          };
          if (includeResponse) {
            resultPayload.response = response;
          }
        } catch (error) {
          resultPayload = {
            isError: true,
            error: error,
            httpCode: response ? response.status : null,
          };
          if (includeResponse && response) {
            resultPayload.response = response;
          }
        }

        results[index] = resultPayload;
        completed++;

        if (typeof onProgress === "function") {
          onProgress({
            completed,
            total,
            item,
            isError: resultPayload.isError,
            httpCode: resultPayload.httpCode,
            error: resultPayload.error,
            response: response,
            data: resultPayload.data,
          });
        }
      }
    };

    const workers = [];
    const poolSize = Math.min(concurrency, total);
    for (let i = 0; i < poolSize; i++) {
      workers.push(worker());
    }

    await Promise.all(workers);
    return results;
  }

  /**
   * Processes an array of items in parallel batches using the legacy positional arguments signature.
   * Internally maps parameters and calls the modern batch() method.
   * 
   * @deprecated Use batch() instead.
   * @param {string} [url=undefined]
   * @param {string} [method="GET"]
   * @param {Array<any>} [items=[]]
   * @param {Object} [headers={}]
   * @param {Object} [options={}]
   * @param {Object} [config={}]
   * @returns {Promise<Array<{isError: boolean, httpCode: number|null, response?: Response, error?: any}>>}
   */
  async batch_old(
    url = undefined,
    method = "GET",
    items = [],
    headers = {},
    options = {},
    config = {}
  ) {
    return this.batch({
      url,
      method,
      items,
      headers,
      options,
      config,
    });
  }
}

module.exports = uFetch;
