"use strict";

const regexIsAbsolute = /^[a-zA-Z][a-zA-Z\d+\-.]*:/;

/**
 * Dynamically selects fetch from the environment (browser / node)
 * to avoid crashes if a polyfill is loaded later.
 */
const getFetch = () => {
  if (typeof window !== "undefined" && typeof window.fetch === "function") {
    return window.fetch.bind(window);
  }
  if (typeof globalThis !== "undefined" && typeof globalThis.fetch === "function") {
    return globalThis.fetch.bind(globalThis);
  }
  throw new Error("fetch is not defined. Please verify your environment or add a polyfill.");
};

const validMethods = new Set([
  "GET",
  "POST",
  "PUT",
  "PATCH",
  "DELETE",
  "HEAD",
  "OPTIONS",
  "CONNECT",
  "TRACE",
]);

/**
 * uFetch class: Universal and AI-friendly wrapper for HTTP requests (based on 'fetch').
 * Provides tools to automatically handle relative/absolute URLs, JSON bodies,
 * Authorization headers, Query parameters and abstracts the environment context (Browser vs NodeJS).
 */
class uFetch {
  /**
   * Initializes the HTTP client instance.
   * @param {string} [url=undefined] - (Optional) Default base URL to use in requests.
   * @param {string} [redirect_in_unauthorized=undefined] - (Optional) Route or URL to automatically redirect the client in case of 401 error (Only in Browser environment with window).
   */
  constructor(url = undefined, redirect_in_unauthorized = undefined) {
    this._redirect_in_unauthorized_internal = redirect_in_unauthorized;
    this._basic_authentication = undefined;
    this._bearer_authentication = undefined;
    this._url = url;
    this._defaultHeaders = new Map();

    if (typeof AbortController !== "undefined") {
      this._abortController = new AbortController();
    }
  }

  /**
   * Immediately cancels all in-progress requests generated by this instance
   * that do not have an explicitly overridden AbortSignal. 
   * Internally resets to a new controller to support immediate subsequent requests.
   * @param {any} [reason] - Reason, message, or exception returned in the promise rejection catch (e.g., AbortError).
   */
  abort(reason) {
    if (this._abortController) {
      this._abortController.abort(reason);
      this._abortController = new AbortController();
    }
  }

  /**
   * Configures Basic Auth credentials at the client instance level, injecting them into 'Authorization'.
   * @param {string} username - Plain text username.
   * @param {string} password - Plain text password.
   * @returns {uFetch} Returns the current instance enabling context chaining.
   */
  setBasicAuthorization(username, password) {
    if (
      !username ||
      !password ||
      typeof username !== "string" ||
      typeof password !== "string"
    ) {
      this._basic_authentication = undefined;
      return this;
    }

    const credentials = `${username}:${password}`;
    const base64 =
      typeof Buffer !== "undefined"
        ? Buffer.from(credentials).toString("base64")
        : btoa(credentials);

    this._basic_authentication = `Basic ${base64}`;
    this._bearer_authentication = undefined;
    return this;
  }

  /**
   * @deprecated Use setBasicAuthorization() instead.
   */
  SetBasicAuthorization(username, password) {
    console.warn("DeprecationWarning: uFetch.SetBasicAuthorization() is deprecated. Use uFetch.setBasicAuthorization() instead.");
    return this.setBasicAuthorization(username, password);
  }

  /**
   * @deprecated Use clearAuthorizationHeader() instead.
   */
  ClearAuthorizationHeader() {
    console.warn("DeprecationWarning: uFetch.ClearAuthorizationHeader() is deprecated. Use uFetch.clearAuthorizationHeader() instead.");
    this.clearAuthorizationHeader();
  }

  /**
   * Explicitly completely clears and revokes all authorization headers 
   * stored in memory for this instance (both Basic and Bearer auth).
   */
  clearAuthorizationHeader() {
    this._basic_authentication = undefined;
    this._bearer_authentication = undefined;
  }

  /**
   * Alias for setBasicAuthorization for convenience.
   * @param {string} user 
   * @param {string} password 
   * @returns {uFetch}
   */
  setBasicAuthentication(user, password) {
    return this.setBasicAuthorization(user, password);
  }

  /**
   * @deprecated Use setBasicAuthentication() instead.
   */
  SetBasicAuthentication(user, password) {
    console.warn("DeprecationWarning: uFetch.SetBasicAuthentication() is deprecated. Use uFetch.setBasicAuthentication() instead.");
    return this.setBasicAuthentication(user, password);
  }

  /**
   * Configures a Bearer token for the 'Authorization' header at the instance level.
   * Its activation will explicitly deactivate/overwrite any previously persisted Basic credential.
   * @param {string} key - Token key (e.g., a pure JWT or Access Hash).
   * @returns {uFetch} Returns the class for context chaining.
   */
  setBearerAuthorization(key) {
    this._bearer_authentication = key ? `Bearer ${key}` : undefined;
    if (key) this._basic_authentication = undefined;
    return this;
  }

  /**
   * Adds a global, permanent, and persistent header that will be attached to all future
   * peticiones invocadas por este objeto `uFetch`.
   * @param {string} key - Name of the HTTP header block (e.g. 'Application-Context').
   * @param {string} value - String value of the header.
   */
  addHeader(key, value) {
    this._defaultHeaders.set(key, value);
  }

  _addAuthorizationHeader(headers) {
    if (this._basic_authentication) {
      headers.set("Authorization", this._basic_authentication);
    } else if (this._bearer_authentication) {
      headers.set("Authorization", this._bearer_authentication);
    } else if (headers.get('Authorization')) {
      headers.set("Authorization", headers.get('Authorization'));
    } else {
      headers.delete("Authorization");
    }
  }

  _normalizeHeaders(headers = {}, data = undefined) {
    const h = new Headers();

    // Helper to add headers from various sources
    const addFn = (v, k) => h.append(k, v);

    if (headers instanceof Headers || headers instanceof Map) {
      headers.forEach(addFn);
    } else {
      // iterate over object
      for (const [k, v] of Object.entries(headers)) {
        h.append(k, v);
      }
    }

    // agregar headers por defecto
    for (const [k, v] of this._defaultHeaders.entries()) {
      h.set(k, v);
    }

    // auth
    this._addAuthorizationHeader(h);

    if (!h.has("Content-Type")) {
      const isSpecialBody =
        (typeof FormData !== "undefined" && data instanceof FormData) ||
        (typeof Blob !== "undefined" && data instanceof Blob) ||
        (typeof URLSearchParams !== "undefined" && data instanceof URLSearchParams) ||
        (typeof ReadableStream !== "undefined" && data instanceof ReadableStream) ||
        (typeof ArrayBuffer !== "undefined" && data instanceof ArrayBuffer);

      // Only add application/json if data is not special AND not a string
      // strings are strictly treated as raw bodies unless header says otherwise
      if (!isSpecialBody && data != null && typeof data !== "string") {
        h.append("Content-Type", "application/json");
      }
    }

    // Eliminar Content-Length
    h.delete("Content-Length");

    return h;
  }

  _createBody(data) {
    if (data == null) return undefined;

    // casos especiales
    if (
      (typeof FormData !== "undefined" && data instanceof FormData) ||
      (typeof Blob !== "undefined" && data instanceof Blob) ||
      (typeof URLSearchParams !== "undefined" && data instanceof URLSearchParams) ||
      (typeof ReadableStream !== "undefined" && data instanceof ReadableStream) ||
      (typeof ArrayBuffer !== "undefined" && data instanceof ArrayBuffer) ||
      typeof data === "string"
    ) {
      return data;
    }

    // fallback → JSON
    return JSON.stringify(data);
  }

  /**
   * Low-level core engine to execute an asynchronous network request using the Fetch API.
   * Automatically injects Authorization headers and handles smart serialization.
   * 
   * @param {string} url - Final absolute URL, or internal relative path.
   * @param {string} [method="GET"] - HTTP verb in uppercase (GET, POST, PUT, DELETE, PATCH, etc).
   * @param {any} [data=undefined] - The body payload. For GET/HEAD it's sent as a querystring, for other verbs it is automatically converted to a JSON body unless it's a native Stream/Blob/FormData.
   * @param {Object} [headers={}] - Additional dictionary of ephemeral headers living only for this specific transaction.
   * @param {RequestInit} [options={}] - Base object for strict overriding of primitive Fetch options (Credentials, Caching, Mode, custom Signal, etc).
   * @returns {Promise<Response>} Promise resolving to the Fetch Response object.
   * @throws Exception when asynchronous URL validation fails locally or fetch explicitly fails.
   */
  async request(
    url,
    method = "GET",
    data = undefined,
    headers = {},
    options = {},
  ) {
    method = method.toUpperCase();

    if (!validMethods.has(method)) {
      throw new Error("Invalid method");
    }

    let finalURL = url || this._url;

    // URL Validation using try-catch for better compatibility
    const baseURL =
      typeof window !== "undefined" ? window.location.href : "http://localhost";
    try {
      new URL(finalURL, baseURL);
    } catch (e) {
      console.error("Is required a valid URL", finalURL);
      throw new Error("Is required a valid URL " + finalURL);
    }

    const h = this._normalizeHeaders(headers, data);

    // GET / HEAD → data como querystring
    if (["GET", "HEAD"].includes(method) && data && typeof data === "object") {
      const sp = new URLSearchParams(data);
      const queryString = sp.toString();
      if (queryString) {
        const hashIndex = finalURL.indexOf("#");
        let hash = "";
        let urlWithoutHash = finalURL;

        if (hashIndex !== -1) {
          hash = finalURL.substring(hashIndex);
          urlWithoutHash = finalURL.substring(0, hashIndex);
        }

        const separator = urlWithoutHash.includes("?") ? "&" : "?";
        finalURL = urlWithoutHash + separator + queryString + hash;
      }
    }

    const body = !["GET", "HEAD"].includes(method)
      ? this._createBody(data)
      : undefined;

    const opts = {
      method,
      headers: h,
      body,
      ...(this._abortController ? { signal: this._abortController.signal } : {}),
      ...options,
    };

    let response;
    try {
      const fetchImpl = getFetch();
      response = await fetchImpl(finalURL, opts);

      if (
        typeof window !== "undefined" &&
        this._redirect_in_unauthorized_internal &&
        response.status === 401
      ) {
        window.location.href = this._redirect_in_unauthorized_internal;
      }

      return response;
    } catch (err) {
      console.error(err);
      throw err;
    }
  }

  // Simplified Methods

  /**
   * Triggers a read query ("GET" verb). Automatically and transparently serializes `opts.data` using search query strings (e.g., url?foo=bar).
   * @param {{url?: string, data?: any, headers?: Object, options?: RequestInit}} opts - Configuration wrapper object (URL, simulated body Data, local headers and init options).
   * @returns {Promise<Response>} Original HTTP Promise from the `fetch` API.
   */
  get(opts = {}) {
    return this.request(opts.url, "GET", opts.data, opts.headers, opts.options);
  }

  /** @deprecated Use get() instead. */
  GET(opts = {}) {
    console.warn("DeprecationWarning: uFetch.GET() is deprecated. Use uFetch.get() instead.");
    return this.get(opts);
  }

  /**
   * Triggers a mutation/insertion via an endpoint consuming a "POST" verb.
   * By default, stringifies the `data` to JSON without encoding, overriding the 'application/json' flag if it is plain.
   * @param {{url?: string, data?: any, headers?: Object, options?: RequestInit}} opts
   * @returns {Promise<Response>}
   */
  post(opts = {}) {
    return this.request(
      opts.url,
      "POST",
      opts.data,
      opts.headers,
      opts.options,
    );
  }

  /** @deprecated Use post() instead. */
  POST(opts = {}) {
    console.warn("DeprecationWarning: uFetch.POST() is deprecated. Use uFetch.post() instead.");
    return this.post(opts);
  }

  /**
   * Replaces existing information by injecting the complete data payload to the router using the "PUT" verb.
   * @param {{url?: string, data?: any, headers?: Object, options?: RequestInit}} opts
   * @returns {Promise<Response>}
   */
  put(opts = {}) {
    return this.request(opts.url, "PUT", opts.data, opts.headers, opts.options);
  }

  /** @deprecated Use put() instead. */
  PUT(opts = {}) {
    console.warn("DeprecationWarning: uFetch.PUT() is deprecated. Use uFetch.put() instead.");
    return this.put(opts);
  }

  /**
   * Controlled backend partial mutation dictated by the "PATCH" verb, modifying fragments.
   * @param {{url?: string, data?: any, headers?: Object, options?: RequestInit}} opts
   * @returns {Promise<Response>}
   */
  patch(opts = {}) {
    return this.request(
      opts.url,
      "PATCH",
      opts.data,
      opts.headers,
      opts.options,
    );
  }

  /** @deprecated Use patch() instead. */
  PATCH(opts = {}) {
    console.warn("DeprecationWarning: uFetch.PATCH() is deprecated. Use uFetch.patch() instead.");
    return this.patch(opts);
  }

  /**
   * Orders to clear / destroy a resource tuple pointed at by `url` by sending a "DELETE" verb.
   * @param {{url?: string, data?: any, headers?: Object, options?: RequestInit}} opts
   * @returns {Promise<Response>}
   */
  delete(opts = {}) {
    return this.request(
      opts.url,
      "DELETE",
      opts.data,
      opts.headers,
      opts.options,
    );
  }

  /** @deprecated Use delete() instead. */
  DELETE(opts = {}) {
    console.warn("DeprecationWarning: uFetch.DELETE() is deprecated. Use uFetch.delete() instead.");
    return this.delete(opts);
  }

  /**
   * Processes an array of items in parallel batches with a configured concurrency limit.
   * Tolerates individual errors and reports progress dynamically via a Fail-Safe approach.
   * 
   * @param {Array<any>} items - Array of items/parameters to process.
   * @param {Object} config - Configuration object.
   * @param {number} [config.concurrency=5] - Maximum parallel requests running at the same time.
   * @param {string} [config.method="GET"] - Base HTTP method to use if buildRequest doesn't specify one.
   * @param {Function} config.buildRequest - Callback (item) => ({url?, data?, headers?, options?})
   * @param {Function} [config.onProgress] - Callback (info) => void where info contains progress details and response status.
   * @returns {Promise<Array<{isError: boolean, httpCode: number|null, response?: Response, error?: any}>>} Array of mapped responses.
   */
  async batch(items, config = {}) {
    const {
      concurrency = 5,
      method = "GET",
      buildRequest,
      onProgress
    } = config;

    if (!Array.isArray(items)) throw new Error("batch() expects an array of items");
    if (typeof buildRequest !== "function") throw new Error("batch() requires a buildRequest function");

    const total = items.length;
    const results = new Array(total);
    let currentIndex = 0;
    let completed = 0;

    const worker = async () => {
      while (currentIndex < total) {
        const index = currentIndex++;
        const item = items[index];
        let resultPayload;

        try {
          const reqConfig = buildRequest(item);
          const response = await this.request(
            reqConfig.url, 
            reqConfig.method || method, 
            reqConfig.data, 
            reqConfig.headers, 
            reqConfig.options
          );

          resultPayload = {
            isError: false,
            httpCode: response.status,
            response: response,
          };
        } catch (error) {
          resultPayload = {
            isError: true,
            error: error,
            httpCode: null
          };
        }

        results[index] = resultPayload;
        completed++;

        if (typeof onProgress === "function") {
          onProgress({
            completed,
            total,
            item,
            isError: resultPayload.isError,
            httpCode: resultPayload.httpCode,
            error: resultPayload.error,
            response: resultPayload.response
          });
        }
      }
    };

    const workers = [];
    const poolSize = Math.min(concurrency, total);
    for (let i = 0; i < poolSize; i++) {
      workers.push(worker());
    }

    await Promise.all(workers);
    return results;
  }
}

module.exports = uFetch;
